language: go

sudo: false

go:
  - 1.6
  - tip

install:
  # Install our tracked dependencies
  - go get github.com/Masterminds/glide
  - glide install

script:
  - go fmt $(glide novendor)
  - go vet $(glide novendor)
  - go test $(glide novendor)
  - make

matrix:
  allow_failures:
    - go: tip
